### ISSUE TITLE
Check the return code of fread

### ISSUE THREAD

**Issue by kpu** [jnory/DALM#8]
In addition to segfaulting if the file doesn't exist, this code leaves ngramorder and total uninitialized if the file is empty.  The user only sees a very long loop.  The file is empty if ARPA file parsing fails in an earlier step.  Recommend you wrap fread in a function that dies on failure.  

  class ARPAFile {
    public:
      ARPAFile (std::string dumpfile, Vocabulary &vocab) : vocab(vocab){
        fp = std::fopen(dumpfile.c_str(), "rb");

        std::fread(&ngramorder, sizeof(size_t), 1, fp);
        std::fread(&total, sizeof(size_t), 1, fp);

        for(size_t i = 0; i < ngramorder; i++){
          size_t num;
          std::fread(&num, sizeof(size_t), 1, fp);
          ngramnums.push_back(num);
        }
      }

**Comment by jnory** [comment]
Thanks, this is definitely a problem. And I will fix.
(I can take a time for this problem next week.)

**Comment by jnory** [comment]
Done. Moreover, I removed trie_dumper and change the code to read directory from text files.

**Comment by jnory** [comment]
oops, i may inject a bug. I'm fixing now.

**Comment by jnory** [comment]
fix complete. sorry.

**Comment by kpu** [comment]
Thanks.  Though FYI istream is much much slower.

**Comment by jnory** [comment]
Oh, thanks. I changed istream to fgets. faster a bit.
