### ISSUE TITLE
Build fails with python3 as default python

### ISSUE THREAD

**Issue by kpu** [jnory/DALM#9]
Please make your wscript support python3 or change the shebang in waf to python2.  
  File "/home/test/DALM/scripts/wscript", line 13
    bld.install_files('${PREFIX}/scripts', [file], chmod=0755)
SyntaxError: invalid token

**Comment by jnory** [comment]
Thank you for pointing that out.
I changed the shebang to python2.
If you find any problems, please let me know?

Recently, I've just been considering to change build system to CMake.
So, I added an experimental version of CMakelists.txt.
https://github.com/jnory/DALM/commit/0860f24738ccc2981bbe9e77eea768efe50a00f6

**Comment by kpu** [comment]
Now works thanks.  I've heard of people switching from cmake to waf, but not the other way around.
